# coding: utf-8

"""
    OmniCore Model and State Management API

    This is an OmniCore Model and State Management server.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: omnicoresupport@korewireless.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import OmniCore
from OmniCore.models.error_frame import ErrorFrame  # noqa: E501
from OmniCore.rest import ApiException

class TestErrorFrame(unittest.TestCase):
    """ErrorFrame unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ErrorFrame
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ErrorFrame`
        """
        model = OmniCore.models.error_frame.ErrorFrame()  # noqa: E501
        if include_optional :
            return ErrorFrame(
                code = 56, 
                details = '', 
                message = '', 
                status = ''
            )
        else :
            return ErrorFrame(
                code = 56,
                details = '',
                message = '',
                status = '',
        )
        """

    def testErrorFrame(self):
        """Test ErrorFrame"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
