# coding: utf-8

"""
    OmniCore Model and State Management API

    This is an OmniCore Model and State Management server.  # noqa: E501

    The version of the OpenAPI document: 1.8.2
    Contact: omnicoresupport@korewireless.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import OmniCore
from OmniCore.api.sink_api import SinkApi  # noqa: E501
from OmniCore.rest import ApiException


class TestSinkApi(unittest.TestCase):
    """SinkApi unit test stubs"""

    def setUp(self):
        self.api = OmniCore.api.sink_api.SinkApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_sink(self):
        """Test case for create_sink

        """
        pass

    def test_delete_sink(self):
        """Test case for delete_sink

        """
        pass

    def test_get_a_sink(self):
        """Test case for get_a_sink

        """
        pass

    def test_get_sinks(self):
        """Test case for get_sinks

        Get All Sinks  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
