# coding: utf-8

"""
    OmniCore Model and State Management API

    This is an OmniCore Model and State Management server.  # noqa: E501

    The version of the OpenAPI document: 1.8.6
    Contact: omnicoresupport@korewireless.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import OmniCore
from OmniCore.models.log_level import LogLevel  # noqa: E501
from OmniCore.rest import ApiException

class TestLogLevel(unittest.TestCase):
    """LogLevel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLogLevel(self):
        """Test LogLevel"""
        # inst = LogLevel()

if __name__ == '__main__':
    unittest.main()
