# coding: utf-8

"""
    OmniCore Model and State Management API

    This is an OmniCore Model and State Management server.  # noqa: E501

    The version of the OpenAPI document: 1.8.7
    Contact: omnicoresupport@korewireless.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import OmniCore
from OmniCore.models.vault_status_details import VaultStatusDetails  # noqa: E501
from OmniCore.rest import ApiException

class TestVaultStatusDetails(unittest.TestCase):
    """VaultStatusDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test VaultStatusDetails
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VaultStatusDetails`
        """
        model = OmniCore.models.vault_status_details.VaultStatusDetails()  # noqa: E501
        if include_optional :
            return VaultStatusDetails(
                subscription_id = '', 
                storage_type = '', 
                is_enabled = True, 
                is_created = True, 
                updatedon = '', 
                created_on = '', 
                mqtt_id = '', 
                retention_period = 56, 
                encryption_key_id = 56, 
                is_encrypted = True
            )
        else :
            return VaultStatusDetails(
        )
        """

    def testVaultStatusDetails(self):
        """Test VaultStatusDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
