# coding: utf-8

"""
    OmniCore Model and State Management API

    This is an OmniCore Model and State Management server.  # noqa: E501

    The version of the OpenAPI document: 1.8.5
    Contact: omnicoresupport@korewireless.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import OmniCore
from OmniCore.models.configurations import Configurations  # noqa: E501
from OmniCore.rest import ApiException

class TestConfigurations(unittest.TestCase):
    """Configurations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Configurations
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Configurations`
        """
        model = OmniCore.models.configurations.Configurations()  # noqa: E501
        if include_optional :
            return Configurations(
                details = [
                    OmniCore.models.vault_configuration.VaultConfiguration(
                        id = 56, 
                        subscription = '', 
                        type = '', 
                        data = '', )
                    ]
            )
        else :
            return Configurations(
        )
        """

    def testConfigurations(self):
        """Test Configurations"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
