# coding: utf-8

"""
    OmniCore Model and State Management API

    This is an OmniCore Model and State Management server.  # noqa: E501

    The version of the OpenAPI document: 1.8.3
    Contact: omnicoresupport@korewireless.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import OmniCore
from OmniCore.models.audit import Audit  # noqa: E501
from OmniCore.rest import ApiException

class TestAudit(unittest.TestCase):
    """Audit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Audit
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Audit`
        """
        model = OmniCore.models.audit.Audit()  # noqa: E501
        if include_optional :
            return Audit(
                subscription_id = '', 
                operation = '', 
                actor = '', 
                updatedon = ''
            )
        else :
            return Audit(
        )
        """

    def testAudit(self):
        """Test Audit"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
