# coding: utf-8

"""
    OmniCore Model and State Management API

    This is an OmniCore Model and State Management server.  # noqa: E501

    The version of the OpenAPI document: 1.8.7
    Contact: omnicoresupport@korewireless.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import OmniCore
from OmniCore.models.policy import Policy  # noqa: E501
from OmniCore.rest import ApiException

class TestPolicy(unittest.TestCase):
    """Policy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Policy
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Policy`
        """
        model = OmniCore.models.policy.Policy()  # noqa: E501
        if include_optional :
            return Policy(
                connect = True, 
                publish_state = True, 
                publish_events = True, 
                publish_events_regex = '', 
                publish_loopback = True, 
                subscribe_command = True, 
                subscribe_command_regex = '', 
                subscribe_broadcast = True, 
                subscribe_broadcast_regex = '', 
                subscribe_config = True
            )
        else :
            return Policy(
                connect = True,
                publish_state = True,
                publish_events = True,
                publish_events_regex = '',
                publish_loopback = True,
                subscribe_command = True,
                subscribe_command_regex = '',
                subscribe_broadcast = True,
                subscribe_broadcast_regex = '',
                subscribe_config = True,
        )
        """

    def testPolicy(self):
        """Test Policy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
