# coding: utf-8

"""
    OmniCore Model and State Management API

    This is an OmniCore Model and State Management server.  # noqa: E501

    The version of the OpenAPI document: 1.8.11
    Contact: omnicoresupport@korewireless.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import OmniCore
from OmniCore.models.list_devices_online_response import ListDevicesOnlineResponse  # noqa: E501
from OmniCore.rest import ApiException

class TestListDevicesOnlineResponse(unittest.TestCase):
    """ListDevicesOnlineResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ListDevicesOnlineResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListDevicesOnlineResponse`
        """
        model = OmniCore.models.list_devices_online_response.ListDevicesOnlineResponse()  # noqa: E501
        if include_optional :
            return ListDevicesOnlineResponse(
                devices = [
                    OmniCore.models.device_online.DeviceOnline(
                        id = '012', 
                        registry = '', 
                        client_online = True, 
                        last_heartbeat_time = '', 
                        subscription = '', )
                    ], 
                page_number = 56, 
                page_size = 56, 
                total_count = 56
            )
        else :
            return ListDevicesOnlineResponse(
                devices = [
                    OmniCore.models.device_online.DeviceOnline(
                        id = '012', 
                        registry = '', 
                        client_online = True, 
                        last_heartbeat_time = '', 
                        subscription = '', )
                    ],
        )
        """

    def testListDevicesOnlineResponse(self):
        """Test ListDevicesOnlineResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
