# coding: utf-8

"""
    OmniCore Model and State Management API

    This is an OmniCore Model and State Management server.  # noqa: E501

    The version of the OpenAPI document: 1.8.3
    Contact: omnicoresupport@korewireless.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import OmniCore
from OmniCore.models.enable_vault import EnableVault  # noqa: E501
from OmniCore.rest import ApiException

class TestEnableVault(unittest.TestCase):
    """EnableVault unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test EnableVault
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnableVault`
        """
        model = OmniCore.models.enable_vault.EnableVault()  # noqa: E501
        if include_optional :
            return EnableVault(
                type = 'GCS', 
                action = 'enable'
            )
        else :
            return EnableVault(
                type = 'GCS',
                action = 'enable',
        )
        """

    def testEnableVault(self):
        """Test EnableVault"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
