# coding: utf-8

"""
    OmniCore Model and State Management API

    This is an OmniCore Model and State Management server.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@korewireless.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Dict, List, Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr, constr
from OmniCore.models.device_config import DeviceConfig
from OmniCore.models.device_credential import DeviceCredential
from OmniCore.models.gateway_config import GatewayConfig
from OmniCore.models.log_level import LogLevel

class CreateNewDevice(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    id: constr(strict=True, max_length=256, min_length=3) = ...
    blocked: Optional[StrictBool] = None
    credentials: Optional[List[DeviceCredential]] = None
    gateway_config: Optional[GatewayConfig] = Field(None, alias="gatewayConfig")
    config: Optional[DeviceConfig] = None
    log_level: Optional[LogLevel] = Field(None, alias="logLevel")
    metadata: Optional[Dict[str, StrictStr]] = None
    __properties = ["id", "blocked", "credentials", "gatewayConfig", "config", "logLevel", "metadata"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CreateNewDevice:
        """Create an instance of CreateNewDevice from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in credentials (list)
        _items = []
        if self.credentials:
            for _item in self.credentials:
                if _item:
                    _items.append(_item.to_dict())
            _dict['credentials'] = _items
        # override the default output from pydantic by calling `to_dict()` of gateway_config
        if self.gateway_config:
            _dict['gatewayConfig'] = self.gateway_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of config
        if self.config:
            _dict['config'] = self.config.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CreateNewDevice:
        """Create an instance of CreateNewDevice from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return CreateNewDevice.parse_obj(obj)

        _obj = CreateNewDevice.parse_obj({
            "id": obj.get("id"),
            "blocked": obj.get("blocked"),
            "credentials": [DeviceCredential.from_dict(_item) for _item in obj.get("credentials")] if obj.get("credentials") is not None else None,
            "gateway_config": GatewayConfig.from_dict(obj.get("gatewayConfig")) if obj.get("gatewayConfig") is not None else None,
            "config": DeviceConfig.from_dict(obj.get("config")) if obj.get("config") is not None else None,
            "log_level": obj.get("logLevel"),
            "metadata": obj.get("metadata")
        })
        return _obj

