# coding: utf-8

"""
    OmniCore Model and State Management API

    This is an OmniCore Model and State Management server.  # noqa: E501

    The version of the OpenAPI document: 1.8.7
    Contact: omnicoresupport@korewireless.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr

class DeviceConfig(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    acknowledged: Optional[StrictBool] = None
    binary_data: Optional[StrictStr] = Field(None, alias="binaryData", description="Base64 Encoded Comnfig String")
    cloud_update_time: Optional[StrictStr] = Field(None, alias="cloudUpdateTime")
    device_ack_time: Optional[StrictStr] = Field(None, alias="deviceAckTime")
    version: Optional[StrictInt] = None
    __properties = ["acknowledged", "binaryData", "cloudUpdateTime", "deviceAckTime", "version"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DeviceConfig:
        """Create an instance of DeviceConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DeviceConfig:
        """Create an instance of DeviceConfig from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return DeviceConfig.parse_obj(obj)

        _obj = DeviceConfig.parse_obj({
            "acknowledged": obj.get("acknowledged"),
            "binary_data": obj.get("binaryData"),
            "cloud_update_time": obj.get("cloudUpdateTime"),
            "device_ack_time": obj.get("deviceAckTime"),
            "version": obj.get("version")
        })
        return _obj

