# coding: utf-8

"""
    OmniCore Model and State Management API

    This is an OmniCore Model and State Management server.  # noqa: E501

    The version of the OpenAPI document: 1.8.11
    Contact: omnicoresupport@korewireless.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr, constr

class DeviceOnline(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    id: constr(strict=True, max_length=256, min_length=3) = ...
    registry: Optional[StrictStr] = None
    client_online: Optional[StrictBool] = Field(None, alias="clientOnline")
    last_heartbeat_time: Optional[StrictStr] = Field(None, alias="lastHeartbeatTime")
    subscription: Optional[StrictStr] = None
    __properties = ["id", "registry", "clientOnline", "lastHeartbeatTime", "subscription"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DeviceOnline:
        """Create an instance of DeviceOnline from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "registry",
                            "client_online",
                            "last_heartbeat_time",
                            "subscription",
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DeviceOnline:
        """Create an instance of DeviceOnline from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return DeviceOnline.parse_obj(obj)

        _obj = DeviceOnline.parse_obj({
            "id": obj.get("id"),
            "registry": obj.get("registry"),
            "client_online": obj.get("clientOnline"),
            "last_heartbeat_time": obj.get("lastHeartbeatTime"),
            "subscription": obj.get("subscription")
        })
        return _obj

